### ISSUE TITLE
Mapear funcionalidades que podem ser implementadas no frontend dessa edição

### ISSUE THREAD

**Issue by jhonnye0** [IC-Apps-CCA/GestIC-vCancer#4]

**Comment by ricardoalves1** [comment]
# Melhorias

## Geral
- Imagem de perfil no registro é salva como um arquivo no frontend (deveria estar salvo pelo menos no backend, de preferência com um s3 da vida, mas arquivo local serve tbm)

## Backend
- Retornos das APIs quando possuem 'password', estão retornando asteriscos.
- Todos os retornos de erro estão genéricos (HTTP 500 Internal Server Error)

## Frontend
- Todas as mensagens de erro estão genéricas.
- Validação do formulário de registro não verifica se os campos só possuem espaços. (Colocar um *trim* para validar)
- Remover pasta de `src/uploads`
- Remover `console.log` desnecessários
- Cadastro possui `nome` e `sobrenome` mas o backend suporta somente `nome`, o correto é retirar o campo sobrenome e deixar somente 1.
- Lista de emails está fixa no código, o correto é tudo vir do backend
- Não está sendo feita a requisição para listagem de emails, pois o backend não possui a implementação para tal.
    - `/frontend/src/pages/UsefulInformations/EmailList/index.tsx`
- Refatorar `/frontend/src/pages/UsefulInformations/Page/index.tsx`
- Talvez seja bom ter uma forma de voltar as páginas
- Input de `Informações` na tela de `Novo evento` deve ser de tamanho automático, com tamanho máximo fixo e com scroll quando necessário.
- O calendário está em inglês
- Filtro de eventos está sendo feito pelo frontend, o correto é utilizar o backend para retornar os dados de acordo com a busca.
- Talvez seja bom ter a opção de listagem de eventos sem passar pela tela de Calendário
- Filtro de projetos ativos está sendo feito no front
- Informações do projeto está incompleta e não existe edição e criação e deleção
- Filtro de grupo de pesquisa está sendo feito no front
- - Alterar formularios para não possuirem text-area
- - Filtro de atividades complementares está sendo feito no front
- Na tabela de atividades complementares a coluna de aluno possui o uuid dele, o ideal era que fosse o nome/email
