### ISSUE TITLE
Deployment da aplicação no herokuapp

### ISSUE THREAD

**Issue by jhonnye0** [IC-Apps-CCA/GestIC-vCancer#43]

**Comment by samuel0072** [comment]
Fiz um deploy de teste no perfil pessoal. O Backend funcionou corretamente. No front-end houve problemas com relação ao uso de memória RAM da aplicação. Isso precisa ser investigado melhor.

**Comment by samuel0072** [comment]
Ficou decidido que apenas o backend vai ser hospedado no heroku
