### ISSUE TITLE
Mapear possíveis bug no frontend

### ISSUE THREAD

**Issue by jhonnye0** [IC-Apps-CCA/GestIC-vCancer#6]

**Comment by paulobernardoaf** [comment]
# Bugs

## Backend

- Endpoint de registro está quebrado.
    - `/backend/src/services/User.js:96`
- Informações do evento não estão sendo salvas.
- Ao editar perfil, caso seja enviada no campo `senha antiga` uma senha inválida, a requisição do backend retorna sucesso, mas a alteração não é feita no banco.

## Frontend

- Na tela de registro, caso o campo de sobrenome esteja vazio, o erro aparece também no campo de título
- Caso um erro aconteça durante o login, um alerta do navegador aparece, além do alerta que o site provê.
    - `/frontend/src/providers/AuthProvider/index.tsx:75`
- Requisição de envio de imagem sendo feita desnecessáriamente caso uma imagem não seja escolhida
- Painel de usuário está com dados fixos/errados
- Fonte da tela de painel de usuário está quebrada
- Seletor de ir para perfil só funciona caso seja clicado no texto
- Ao fazer sign out não é redirecionado para a tela de login.
- A visualização do calendario no tipo `week` está quebrada quando existe um evento cadastrado naquela semana.
- Tela criação de evento está sendo mostrada para usuarios do tipo aluno, mas um aluno não pode criar eventos.
- Botão de editar evento está com texto errado
- Tela de editar grupo de pesquisa está com titulo errado.
- A opção de editar e apagar grupo de pesquisa aparece para usuarios que não possuem essa permissão (mas a ação não é executada).
- A opção de adicionar horário aparece para usuarios que não possuem essa permissão
- É possivel editar e apagar horário mesmo sendo monitor e aluno (em tese seria possivel somente um admin/professor)
- É necessário alterar todos os formularios para não permitirem somente espaço em branco.
- Formulário de criação de atividades complentares está incorreto, permitindo texto nos campos de data
- Após a criação de uma atividade complementar o usuário não é redirecionado para a tela de listagem.
- Link para visualização de uma única atividade complementar está quebrado/redirecionando para a home
- Menu lateral não mostra todas as opções, está faltando atividades complementares e montar horario.
- Informativos aparece somente no menu lateral
- A opçao de criar informativos aparece para quem não possui permissão
- A opção de editar informativo está quebrada.
